#!/bin/bash

# ROS2 Foxy

# Set noninteractive for building
export DEBIAN_FRONTEND=noninteractive

# Fetch latest package lists and upgrade installed packages
printf "\nUpgrading current packages..\n\n" && sleep 5
apt update
apt upgrade -y

# Install git and python
apt install -y git python3 python3-pip

# Setup character encoding
apt install -y locales
locale-gen en_US en_US.UTF-8
update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8

# Fetch git repositories
printf "\nCheckout Desktop Robotti git repository..\n\n" && sleep 5
cd ~
git clone https://gitlab.au.dk/desktop_robotti/drobotti-processing-and-control.git
cd drobotti-processing-and-control
git checkout c8628ea11608d78745b9d7815aa33824495ba398
# Install Java 17 for Maestro
printf "\nInstalling Java 17 for Maestro simulation..\n\n" && sleep 5
apt install -y openjdk-17-jre

# Make ROS2 Apt repository available
printf "\nFetching ROS2 repository..\n\n" && sleep 5
apt install -y software-properties-common
add-apt-repository universe
apt install -y curl
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && printf $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# ROS2 
printf "\nInstalling ROS2..\n\n" && sleep 5
apt update
apt upgrade -y
apt install -y ros-foxy-desktop python3-argcomplete ros-dev-tools

# Install FMU dependencies
printf "\nInstalling FMU dependencies..\n\n" && sleep 5
python -m pip install -U zmq protobuf==3.19.0
python -m pip install pika scipy

# Install Ros ackermann msgs
printf "\nInstalling ROS ackermann msgs..\n\n" && sleep 2
apt install ros-foxy-ackermann-msgs

# Build rmq ros client message broker
printf "\nBuilding FMU bridge and teleoperation controller node..\n\n" && sleep 5
cd ~/drobotti-processing-and-control
rosdep init
rosdep update
source /opt/ros/foxy/setup.bash
rosdep install --from-paths src --ignore-src -r -y --rosdistro foxy
colcon build --symlink-install --packages-select rmq_bridge teleop