#!/bin/sh

export DEBIAN_FRONTEND=noninteractive

# Fetch latest package lists and upgrade installed packages 
apt update
apt upgrade -y


# Setup character encoding
apt install -y locales
locale-gen en_US en_US.UTF-8
update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8

# Install git
apt install -y git

# Fetch git repositories
cd ~
git clone https://gitlab.au.dk/desktop_robotti/drobotti-intocps.git
git clone hhttps://gitlab.au.dk/desktop_robotti/drobotti-processing-and-control.git

# Install Java 17 for Maestro
apt install -y openjdk-17-jre 

# Install ROS2 Apt repository
apt install -y software-properties-common
add-apt-repository universe
apt install -y curl
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# ROS2 dependencies
apt update
apt install -y \
  python3-flake8-docstrings \
  python3-pip \
  python3-pytest-cov \
  ros-dev-tools
python3 -m pip install -U \
   flake8-blind-except \
   flake8-builtins \
   flake8-class-newline \
   flake8-comprehensions \
   flake8-deprecated \
   flake8-import-order \
   flake8-quotes \
   "pytest>=5.3" \
   pytest-repeat \
   pytest-rerunfailures

# Download ROS2 source code
mkdir -p ~/ros2_humble
cd ~/ros2_humble
vcs import --input https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos src

# Build ROS2
rosdep init
rosdep update
rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"
colcon build --symlink-install

