#!/bin/bash

# install openmodelica
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo curl -fsSL http://build.openmodelica.org/apt/openmodelica.asc | \
  sudo gpg --dearmor -o /usr/share/keyrings/openmodelica-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/openmodelica-keyring.gpg] \
  https://build.openmodelica.org/apt \
  focal \
  stable" | sudo tee /etc/apt/sources.list.d/openmodelica.list
sudo apt update
sudo apt install --no-install-recommends omc

# install python3.10
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.10
sudo curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
sudo python3.10 -m pip install --upgrade pip

# install requirements for the project
apt-get install build-essential libssl-dev libffi-dev python3-dev
python3.10 -m pip install -r lifecycle/requirements_linux.txt

