image: fedora:41

stages:
  - triggers

trigger_mass-spring-damper:
  stage: triggers
  trigger:
    include: digital_twins/mass-spring-damper/.gitlab-ci.yml
  rules: 
    - if: '$DTName == "mass-spring-damper"'
      when: always
  variables:
    RunnerTag: $RunnerTag

trigger_heart_dt:
  stage: triggers
  trigger:
    include: digital_twins/heart_dt/.gitlab-ci.yml
  rules:
    - if: '$DTName == "heart_dt"'
      when: always
  variables:
    RunnerTag: $RunnerTag
