#!/bin/bash 

# exit if a command fails
set -e

if [ -z "$O5G_INSTALL_PATH" ]; then
  O5G_INSTALL_PATH="/workspace/examples"
  printf "Installing to ${O5G_INSTALL_PATH}, \
	set O5G_INSTALL_PATH to overwrite"
fi

source "${O5G_INSTALL_PATH}/digital_twins/o5g/config"

printf "Compiling fmu from OpenModelica model \n"

cd "${O5G_INSTALL_PATH}/models"
omc "${O5G_INSTALL_PATH}/models/makefmu.mos"

chmod +x "${O5G_INSTALL_PATH}/digital_twins/o5g/runTessla.sh"

if [ "$O5G_SETUP_GRAFANA" = "true" ]; then

  printf "Create Grafana datasource\n\n"
  cd "${O5G_INSTALL_PATH}/digital_twins/o5g"

  source_uid=$(curl -X POST -H "Content-Type: application/json" \
	-H "Authorization: Bearer $GRAFANA_TOKEN" \
	--data-binary "@grafana-connection.json" \
	"$O5G_GRAFANA_SERVER/api/datasources" | tee | \
	jq -r '.datasource.uid')

  sed "s/\$source_uid/${source_uid}/" \
	grafana-dashboard-template.json > temp.json
  mv temp.json grafana-dashboard.json

  printf "Create Grafana visulization dashboard"

  curl -X POST -H "Content-Type: application/json" \
	-H "Authorization: Bearer $O5G_GRAFANA_TOKEN" \
	--data-binary "@grafana-dashboard.json" \
	"$O5G_GRAFANA_SERVER/api/dashboards/db"

fi
printf "\n\nDone installing, use execute script to run \
	digital twin \n"
