#!/bin/bash

SESSION_NAME="o5g"

if [ -z "$O5G_INSTALL_PATH" ]; then
  O5G_INSTALL_PATH="/workspace/examples"
fi

# Check if the session exists, discarding output
# We're just looking for the exit code
tmux has-session -t $SESSION_NAME 2>/dev/null

# If the session does not exist, create it
if [ $? != 0 ]; then
  
  tmux new-session -d -s $SESSION_NAME \; \split-window -v \; \split-window -h \; \select-pane -t 0 \; \split-window -h

  # Start the first Python script in the left pane
  tmux send-keys -t ${SESSION_NAME}.0 "export O5G_INSTALL_PATH=${O5G_INSTALL_PATH} && source ${O5G_INSTALL_PATH}/digital_twins/o5g/config && python3 ${O5G_INSTALL_PATH}/digital_twins/o5g/sensorSimulation.py" C-m

  # Start the second Python script in the right pane
  tmux send-keys -t ${SESSION_NAME}.1 "export O5G_INSTALL_PATH=${O5G_INSTALL_PATH} && source ${O5G_INSTALL_PATH}/digital_twins/o5g/config && python3 ${O5G_INSTALL_PATH}/digital_twins/o5g/main.py" C-m

  tmux send-keys -t ${SESSION_NAME}.2 "export O5G_INSTALL_PATH=${O5G_INSTALL_PATH} && source ${O5G_INSTALL_PATH}/digital_twins/o5g/config && telegraf --config ${O5G_INSTALL_PATH}/digital_twins/o5g/telegraf.conf" C-m

  tmux send-keys -t ${SESSION_NAME}.3 "${O5G_INSTALL_PATH}/digital_twins/o5g/runTessla.sh" C-m
fi

echo "Scripts started in tmux session $SESSION_NAME."
