#!/bin/bash

SESSION_NAME="o5g"

# Check if the session exists, discarding output
# We're just looking for the exit code
tmux has-session -t $SESSION_NAME 2>/dev/null

# If the session does not exist, create it
if [ $? != 0 ]; then
  
  tmux new-session -d -s $SESSION_NAME \; \split-window -v \; \split-window -h \; \select-pane -t 0 \; \split-window -h

  # Start the first Python script in the left pane
  tmux send-keys -t ${SESSION_NAME}.0 'python3 /workspace/digital_twins/o5g/sensorSimulation.py' C-m

  # Start the second Python script in the right pane
  tmux send-keys -t ${SESSION_NAME}.1 'python3 /workspace/digital_twins/o5g/main.py' C-m

  tmux send-keys -t ${SESSION_NAME}.2 'telegraf --config /workspace/digital_twins/o5g/telegraf.conf' C-m

  tmux send-keys -t ${SESSION_NAME}.3 '/workspace/digital_twins/o5g/runTessla.sh' C-m
fi

echo "Scripts started in tmux session $SESSION_NAME."
