#!/bin/bash

set -e  # fail fast on errors

printf "install dependencies and create configuration \n\n"
export DEBIAN_FRONTEND=noninteractive

# Update and install sudo
apt update
apt install -y sudo
sudo apt-get update

# Install tzdata BEFORE reconfiguring it
sudo apt-get install -y tzdata

# Preconfigure tzdata (no interactive prompt)
sudo ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
echo "Asia/Kolkata" | sudo tee /etc/timezone
sudo dpkg-reconfigure -f noninteractive tzdata

# Install rest
sudo apt-get install -y openjdk-17-jre
