stages:
  - run

heart_dt_run:
  stage: run
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    IMAGE_NAME: heart_dt_image
  script:
    - docker info
    - cd digital_twins/heart_dt
    - cd ../../
    - docker build -f digital_twins/heart_dt/Dockerfile -t $IMAGE_NAME .
    - docker run -d -p 5001:5001 --name heart_dt_container $IMAGE_NAME
  # tags:
  #   - $RunnerTag
