#!/bin/bash

start_time=$(date +%s)

echo "Running create..."
bash lifecycle/create

echo "Running execute..."
bash lifecycle/execute

end_time=$(date +%s)
elapsed=$((end_time - start_time))
echo "Total time: $elapsed seconds"

echo "Running clean..."
bash lifecycle/clean

