#!/bin/bash

printf "Plotting results"
mkdir -p /builds/pranjayyelkotwar26/dtaas_examples/data/water_tank_FI/output/plots
python3 lifecycle/plot.py
mv *.png /builds/pranjayyelkotwar26/dtaas_examples/data/water_tank_FI/output/plots