#!/bin/sh

printf Configuring extension
export MAESTRO="/workspace/examples/common/tools"
export FSP="/workspace/examples/models"
printf "\t Maestro path: $MAESTRO"
printf "\t FMU search path: $FSP"

printf "Generating Mabl specifications - DT with FI"

$MAESTRO/maestro import sg1 $MAESTRO/FaultInject.mabl ./multimodelFI.json \
  ./simulation-config.json -fsp $FSP \
  -output ./generateFI/

printf "Simulating specification with FI"

$MAESTRO/maestro interpret \
  ./generateFI/spec.mabl \
  $MAESTRO/FaultInject.mabl \
  -output /workspace/examples/data/water_tank_FI/output/ 2>&1 | tee out.txt

