#!/bin/sh

echo "Configuring extension"

# Set paths relative to the project directory
export MAESTRO="$CI_PROJECT_DIR/common/tools"
export FSP="$CI_PROJECT_DIR/models"

echo "Maestro path: $MAESTRO"
echo "FMU search path: $FSP"

echo "Generating Mabl specifications - DT with FI"

"$MAESTRO/maestro" import sg1 "$MAESTRO/FaultInject.mabl" "$CI_PROJECT_DIR/digital_twins/water_tank_FI/multimodelFI.json" \
  "$CI_PROJECT_DIR/digital_twins/water_tank_FI/simulation-config.json" -fsp "$FSP" \
  -output "$CI_PROJECT_DIR/data/water_tank_FI/output/generateFI/"

echo "Simulating specification with FI"

"$MAESTRO/maestro" interpret \
  "$CI_PROJECT_DIR/data/water_tank_FI/output/generateFI/spec.mabl" \
  "$MAESTRO/FaultInject.mabl" \
  -output "$CI_PROJECT_DIR/data/water_tank_FI/output/" 2>&1 | tee "$CI_PROJECT_DIR/data/water_tank_FI/output/out.txt"