%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MAIN FILE FOR STOCHASTIC SUBSPACE IDENTIFICATION MODULE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% This is the main file for conducting stochastic (i.e., output-only) subspace
% identification based on vibration measurements. Input must be provided by the
% user. The output is a file containing the estimated eigencharacteristics and
% the parameter "otype", which designates whether the measurements are displace-
% ments (otype=0), velocitites (otype=1), or accelerations (otype=2).
%
% Input (manually provided by the user in the section "Input plugin" below).
%
% Output
%   sys     - txt-file with the estimated eigenfrequencies (in rad/s), damping
%             ratios, and mode shapes at model order n along with otype.
%
% Note(s):
%           - The user must specify the model order in the command window during
%             the run of the code. This can be based on a stabilization diagram
%             that will appear concurrently.
%           - A figure showing the modal assurance criterion (MAC) values and
%             the modal complexity factors (MCFs) will appear. This can be used
%             to assess the quality of the identification.
%           - The example is based on a simulated 5DOF model with Ns = 99,999
%             samples, Fs = 100 Hz, and acceleration output at DOF 1, 3, and 5
%             generated by low-pass filtered (up to mode 3) input at all DOF.
%
% /MDU 13-11-2023
%-------------------------------------------------------------------------------

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Starting commands (no input required)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all; close all; clc;
addpath('Functions','/workspace/examples/data/structural-monitoring/input')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Input plugin (the user plugs in the required input)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
FileName='Acc_5DOF.txt'; % Measurement data file
Fs=100; % Sampling frequency (most likely follows from the data file)
otype=2; % 0=displacements, 1=velocitites, 2=accelerations
nmax=20; % Maximum model order allowable in the subspace identification
nblock=30; % Number of block rows used in the subspace identification (>=nmax)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% System identification routine (no input required)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[sys.omegaS,sys.zetaS,sys.PhiS]=SSI_Data(FileName,Fs,nmax,nblock);
sys.Fs=Fs;
sys.otype=otype;
clearvars -except sys
pathname=fileparts('Results/');
OutputFile=fullfile(pathname,'sys.txt');
save(OutputFile);


