#!/bin/bash
cd /workspace/DTaaS-examples/digital\ twins/drobotti_rmqfmu

rm -rf target\
out.txt\
generate\
publisher-out.txt\

kill $(ps -ef | grep "rmq-publisher.py" | awk '{print $2}')

kill $(ps -ef | grep "consume.py" | awk '{print $2}')

