#!/bin/sh

echo Configuring extension
export MAESTRO="/workspace/common/tools"
export FSP="/workspace/models"
echo "\t Maestro path: $MAESTRO"
echo "\t FMU search path: $FSP"

echo "Generating Mabl specification"

$MAESTRO/maestro import sg1 coe.json multimodel.json -fsp $FSP -output generate/

echo "Run publisher script in other terminal"

python $MAESTRO/rmq-publisher.py 2>&1 | tee publisher-out.txt &

python $MAESTRO/consume.py 2>&1 | tee consume.txt &

echo "Simulating specifications"

$MAESTRO/maestro interpret generate/spec.mabl -output target 2>&1 | tee out.txt
