#!/bin/bash

printf "Plotting results"
mkdir -p /workspace/examples/data/mass-spring-damper-monitor/output/plots
python lifecycle/plot.py
mv result*.png /workspace/examples/data/mass-spring-damper-monitor/output/plots