#!/bin/bash

set -e # Exit on command failure


NURV="/workspace/examples/common/tools/NuRV/NuRV"
FMI2_HEADERS="/workspace/examples/common/fmi2_headers"


echo "Installing dependencies and create configuration \n\n"

sudo apt-get update
sudo apt-get install -y openjdk-17-jre
pip install pandas matplotlib
sudo apt-get install -y zip


"$NURV" -quiet -source lifecycle/synthesis_m2_fmu.cmd
sed -i 's\Enumeration declaredType="eu.fbk.nurv.RV_value"\Integer\g' \
    m2/modelDescription.xml

FMI2_HOME=$FMI2_HEADERS make -C m2 linux64
mv m2.fmu /workspace/examples/models/m2.fmu