#!/bin/bash

set -e # Exit on command failure

export LIFECYCLE_PATH=${LIFECYCLE_PATH:=$(realpath "$(dirname "${BASH_SOURCE[0]}")")}
echo "Using LIFECYCLE_PATH: ${LIFECYCLE_PATH}"
cd "$LIFECYCLE_PATH"
source .venv/bin/activate

export INCUBATOR_PATH=${INCUBATOR_PATH:=$LIFECYCLE_PATH/../../../common/digital_twins/incubator} # Set variable if not manually exported
echo "Using INCUBATOR_PATH: ${INCUBATOR_PATH}"
cp ../simulation.conf "${INCUBATOR_PATH}/simulation.conf" # copy simulation configuration.

export MONITOR_PATH=${MONITOR_PATH:=$LIFECYCLE_PATH/../src} # Set variable if not manually exported
cd "$MONITOR_PATH"
echo "Starting NuRV FMU Monitor Service, see output at /tmp/nurv-fmu-service.log"
python -u NuRVService.py 2>&1 > /tmp/nurv-fmu-service.log &

# Capture the process ID of NuRVService.py
NURV_SERVICE_PID=$!
echo "NuRVService.py PID: ${NURV_SERVICE_PID}"

sleep 5

cd "$LIFECYCLE_PATH"
python execute.py

# Terminate NuRVService.py after execute.py completes
echo "Terminating NuRVService.py with PID: ${NURV_SERVICE_PID}"
kill $NURV_SERVICE_PID