#!/bin/bash

apt update
cd "$(dirname "${BASH_SOURCE[0]}")"
# install packages
apt-get install -y build-essential default-jre-headless python3-venv cargo

if dpkg -l | grep -qw "telegraf"; then
  echo "Telegraf is already installed"
else
  printf "Installing telegraf \n"
  # influxdata-archive_compat.key GPG Fingerprint: 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E
  curl -s https://repos.influxdata.com/influxdata-archive_compat.key > influxdata-archive_compat.key
  echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
  echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | tee /etc/apt/sources.list.d/influxdata.list
  apt-get update && apt-get install telegraf
  rm influxdata-archive_compat.key
fi

: ${INCUBATOR_PATH:=../../../common/digital_twins/incubator} # Set variable if not manually exported
echo "Using INCUBATOR_PATH: ${INCUBATOR_PATH}"

python3 -m venv .venv
source .venv/bin/activate
pip install -r "${INCUBATOR_PATH}/requirements.txt"
