#!/bin/bash

export LIFECYCLE_PATH=${LIFECYCLE_PATH:=$(realpath "$(dirname "${BASH_SOURCE[0]}")")}
echo "Using LIFECYCLE_PATH: ${LIFECYCLE_PATH}"
cd "$LIFECYCLE_PATH"
source .venv/bin/activate

export TESSLA_PATH=${TESSLA_PATH:=$LIFECYCLE_PATH/../../../tools/tessla-telegraf-connector} # Set variable if not manually exported
echo "Using TESSLA_PATH: ${TESSLA_PATH}"
sed "s/<HOST>/$(hostname)/g" <../safe-operation.tessla >$TESSLA_PATH/safe-operation.tessla # fill & copy tessla specification

export INCUBATOR_PATH=${INCUBATOR_PATH:=$LIFECYCLE_PATH/../../../common/digital_twins/incubator} # Set variable if not manually exported
echo "Using INCUBATOR_PATH: ${INCUBATOR_PATH}"
cp ../simulation.conf "${INCUBATOR_PATH}/simulation.conf" # copy simulation configuration.

python make-telegraf-config.py

cd "$TESSLA_PATH"
echo "Starting TeSSLa-Telegraf-Connector, see output at /tmp/tessla.log"
./TesslaTelegrafConnector -i safe-operation.tessla -c telegraf.conf -r 2>&1 > /tmp/tessla.log &
sleep 10

echo "Starting Telegraf "
telegraf --config telegraf.conf 2>&1 > /tmp/telegraf.log &
sleep 10

cd "$LIFECYCLE_PATH"

python execute.py
