#!/bin/bash

# Base relative paths off lifecycle dir
cd "$(dirname "${BASH_SOURCE[0]}")"

cd "../../../tools/tessla-telegraf-connector/"

rm -r ./outputRustProject
rm annotation.json safe-operation.tessla telegraf.conf
echo "Removed tessla-telegraf-connector temp files"

: ${INCUBATOR_PATH:=../../common/digital_twins/incubator} # Set variable if not manually exported
echo "Using INCUBATOR_PATH: ${INCUBATOR_PATH}"
# Go to Incubator path
cd "${INCUBATOR_PATH}"

rm log.log

echo "Removed incubator log file"

rm /tmp/tessla.log /tmp/telegraf.log

echo "Removed tessla & telegraf logs"