rmq_publisher:
  ros__parameters:
    server_hostname: host
    server_username: user
    server_password: pass
    server_port: 5672
    server_vhost: vhost
    exchange_name: "fmi_digital_twin"
    routing_key: "desktoprobotti"
    prefix_topic_name: True
    group_values_by_topic: True
    topic_config:
      /move_cmd:
        type: "ackermann_msgs/msg/AckermannDrive"
        fields: ["steering_angle", "speed"]

teleop:
  ros__parameters:
    topic_name: /move_cmd