stages:
  - build_and_run

build_and_run:
  stage: build_and_run
  image: ubuntu:24.04
  script:
    - chmod +x lifecycle/create lifecycle/execute lifecycle/clean
    - ./lifecycle/create
    - ./lifecycle/execute
    # - ./lifecycle/clean 
  before_script:
    - cd digital_twins/mass-spring-damper
  artifacts:
    paths:
      - data/mass-spring-damper/output/*
    expire_in: 1 hour
  only:
    - main
