stages:
  - build_and_run

build_and_run:
  stage: build_and_run
  image: ubuntu:24.04
  script:
    - chmod +x lifecycle/create lifecycle/execute
    - ./lifecycle/create
    - ./lifecycle/execute
  before_script:
    - cd digital_twins/mass-spring-damper
  after_script:
    - cd digital_twins/mass-spring-damper
    - chmod +x lifecycle/clean
    - ./lifecycle/clean
  artifacts:
    paths:
      - data/mass-spring-damper/output/*
    expire_in: 1 hour
  only:
    - main
