stages:
  - create
  - execute
  - analyze
  - clean

variables:
  IMAGE_TAG: "$CI_REGISTRY_IMAGE/mass-spring-damper:latest"

create:
  stage: create
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    # Try pulling the image
    - |
      if docker pull $IMAGE_TAG; then
        echo "Image exists in registry. Skipping build."
      else
        echo "Image not found. Building and pushing."
        docker build -t $IMAGE_TAG -f digital_twins/mass-spring-damper/Dockerfile digital_twins/mass-spring-damper
        docker push $IMAGE_TAG
      fi
  # tags:
  #   - $RunnerTag
  only:
    - main

execute:
  stage: execute
  image: $CI_REGISTRY_IMAGE/mass-spring-damper:latest
  script:
    - chmod +x lifecycle/execute
    - ./lifecycle/execute
  before_script:
    - cd digital_twins/mass-spring-damper
  artifacts:
    paths:
      - data/mass-spring-damper/output/*
    expire_in: 1 hour
  rules:
    - when: always
  variables:
    GIT_STRATEGY: fetch
  # tags:
  #   - $RunnerTag

clean:
  stage: clean
  image: $CI_REGISTRY_IMAGE/mass-spring-damper:latest
  script:
    - chmod +x lifecycle/clean
    - ./lifecycle/clean
  before_script:
    - cd digital_twins/mass-spring-damper
  # tags:
  #   - $RunnerTag
