# DO NOT EDIT THIS FILE!
#
# Python module Monitor generated by omniidl

import omniORB
omniORB.updateModule("Monitor")

# ** 1. Stub files contributing to this module
import monitor_idl

# ** 2. Sub-modules

# ** 3. End
