#!/bin/bash

# Go to lifecycle dir and source venv
cd "$(dirname "${BASH_SOURCE[0]}")"
source ../.venv/bin/activate

# Go to Incubator path
: ${INCUBATOR_PATH:=../../../common/digital_twins/incubator} # Set variable if not manually exported
echo "Using INCUBATOR_PATH: ${INCUBATOR_PATH}"
cd "${INCUBATOR_PATH}"

python -m startup.start_all_services