#!/bin/bash

# Go to Incubator path
: ${INCUBATOR_PATH:=../../../common/digital_twins/incubator} # Set variable if not manually exported
echo "Using INCUBATOR_PATH: ${INCUBATOR_PATH}"
cd "${INCUBATOR_PATH}"

source .venv/bin/activate
python -m startup.start_all_services