#!/bin/bash
mkdir -p /workspace/data/mass-spring-damper/output

java -jar /workspace/common/tools/maestro-2.3.0-jar-with-dependencies.jar\
  import -output /workspace/data/mass-spring-damper/output\
  --dump-intermediate sg1 cosim.json time.json\
  -i -vi FMI2 output-dir>debug.log 2>&1
