#!/bin/sh

echo Configuring extension
export MAESTRO="/workspace/examples/common/tools"
export FSP="/workspace/examples/models"
export DATA="/workspace/examples/data/drobotti_rmqfmu"
echo "\t Maestro path: $MAESTRO"
echo "\t FMU search path: $FSP"

echo "Generating Mabl specification"

java -jar $MAESTRO/maestro-2.3.0-jar-with-dependencies.jar import sg1 ./coe.json ./multimodel.json -fsp $FSP -output ./generate/

echo "Run publisher script in other terminal"

python $DATA/rmq-publisher.py 2>&1 | tee ./publisher-out.txt &

python $DATA/consume.py 2>&1 | tee ./consume.txt &

echo "Simulating specifications"

java -jar $MAESTRO/maestro-2.3.0-jar-with-dependencies.jar interpret ./generate/spec.mabl -output ./target 2>&1 | tee ./out.txt
