#!/bin/bash
## Runs the main.java file
printf "Executing the Three-Tank Digital Twin case study... \n\n"
java -cp /workspace/examples/tools/DTManager-0.0.1-Maestro.jar \
  /workspace/examples/tools/three-tank/TankMain.java