#!/bin/sh

echo Configuring extension
export MAESTRO="/workspace/common/tools"
export FSP="/workspace/models"
echo "\t Maestro path: $MAESTRO"
echo "\t FMU search path: $FSP"

echo "Generating Mabl specifications - DT with FI"

java -jar $MAESTRO/maestro-2.3.0-jar-with-dependencies.jar import sg1 $MAESTRO/FaultInject.mabl multimodelFI.json simulation-config.json -fsp $FSP -output generateFI/

echo "Simulating specification with FI"

$MAESTRO/maestro-2.3.0-jar-with-dependencies.jar  interpret generateFI/spec.mabl $MAESTRO/FaultInject.mabl -output targetFI 2>&1 | tee out.txt

