#!/bin/sh

echo Configuring extension
export MAESTRO="/workspace/DTaaS-examples/common/tools"
export FSP="/workspace/DTaaS-examples/models"
export FILES="/workspace/DTaaS-examples/digital twins/water_tank_FI"
echo "\t Maestro path: $MAESTRO"
echo "\t FMU search path: $FSP"

echo "Generating Mabl specifications - DT with FI"

java -jar $MAESTRO/faultinject-bundle-1.0.0-SNAPSHOT-jar-with-dependencies.jar import sg1 $MAESTRO/FaultInject.mabl "$FILES"/multimodelFI.json "$FILES"/simulation-config.json -fsp $FSP -output "$FILES"/generateFI/

echo "Simulating specification with FI"

java -jar $MAESTRO/faultinject-bundle-1.0.0-SNAPSHOT-jar-with-dependencies.jar interpret $MAESTRO/FaultInject.mabl "$FILES"/generateFI/spec.mabl -output "$FILES"/targetFI 2>&1 | tee "$FILES"/out.txt

