#!/bin/bash
if [ -d ./data ]; then
    rm -r ./data/*
fi
cd "$(dirname "${BASH_SOURCE[0]}")"
source .venv/bin/activate
export LD_LIBRARY_PATH=/workspace/examples/digital_twins/incubator-NuRV-monitor-service/lifecycle/.venv/lib/python3.8/site-packages/omniorb_py.libs:$LD_LIBRARY_PATH

export INCUBATOR_PATH=${INCUBATOR_PATH:=../../../common/digital_twins/incubator} # Set variable if not manually exported
echo "Using INCUBATOR_PATH: ${INCUBATOR_PATH}"
export NURV_PATH=${NURV_PATH:=../../../tools/NuRV}
echo "Using NURV_PATH: ${NURV_PATH}"
cp ../simulation.conf "${INCUBATOR_PATH}/simulation.conf" # copy simulation configuration.

python execute.py
