#!/bin/bash
printf "Installing dependencies...\n\n"
apt-get update
apt-get install -y default-jre ## Minimum java 1.8
apt-get install -y maven
mvn -f /workspace/examples/tools/TwinManager/pom.xml package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
cp /workspace/examples/tools/TwinManager/target/TwinManagerFramework-0.0.2.jar /workspace/examples/tools/
python -m venv /workspace/examples/tools/flex-cell/requirements/venv
source /workspace/examples/tools/flex-cell/requirements/venv/bin/activate
pip install -r /workspace/examples/tools/flex-cell/requirements/requirements.txt
if [ ! -d /workspace/examples/data/flex-cell/output ]; then
    mkdir /workspace/examples/data/flex-cell/output
fi
if [ ! -d /workspace/examples/data/flex-cell/output/physical_twin ]; then
    mkdir /workspace/examples/data/flex-cell/output/physical_twin
fi